### Teste com dataloader usando EMPENHOS

In [1]:
import os

path = os.path.join(os.path.abspath('..'), 'features')
X_testing_mode = os.path.join(path,'X_testing_mode.npy')

In [34]:
import numpy as np

dataset = np.load(X_testing_mode)

In [ ]:
from torch.utils.data.dataloader import DataLoader, default_collate


static_dataloader = DataLoader(
    dataset,
    batch_size=5,
    collate_fn=default_collate, # Default
    pin_memory=False, # Já é false por Default
    shuffle=False, # os lotes serão na mesma ordem que no original
)
train_dataloader = DataLoader(
    dataset,
    batch_size=5,
    collate_fn=default_collate, # Default
    shuffle=True,
)

In [40]:
for i, batch in enumerate(static_dataloader): # printar os primeiro 3 batches
    print(f"Batch {i+1}:\n{batch}\n")
    if i == 2:
        break
print(f"Batch shape: {batch.shape}")


Batch 1:
tensor([[-0.0289,  0.0650,  0.0181,  ...,  0.6330,  1.3127,  0.1316],
        [-0.0024,  0.0126,  0.0572,  ...,  0.6330,  1.3127,  0.1316],
        [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730],
        [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730],
        [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730]])

Batch 2:
tensor([[-9.4528e-03,  8.3374e-02,  8.2581e-02,  ...,  6.3297e-01,
          1.3127e+00, -3.7298e-01],
        [-2.4357e-03,  1.2566e-02,  5.7220e-02,  ...,  6.3297e-01,
          1.3127e+00, -3.7298e-01],
        [-6.8550e-03,  9.6008e-02,  2.9175e-02,  ...,  6.3297e-01,
         -1.0486e+00, -3.7508e-01],
        [-1.2856e-03,  6.4270e-02,  5.7770e-02,  ...,  6.3297e-01,
         -4.3892e-01, -3.7103e-01],
        [-6.8550e-03,  9.6008e-02,  2.9175e-02,  ...,  6.3297e-01,
         -4.3892e-01, -3.7103e-01]])

Batch 3:
tensor([[-0.0013,  0.0643,  0.0578,  ...,  0.6330, -0.4389, -0.3710],
        [-0.0013,  0.0643,  0.0578

In [47]:
dataset[:5] # são os mesmos que printamos anteriormente, com o static_dataloader (shuffle=False)

# Batch 1:
# tensor([[-0.0289,  0.0650,  0.0181,  ...,  0.6330,  1.3127,  0.1316],
#         [-0.0024,  0.0126,  0.0572,  ...,  0.6330,  1.3127,  0.1316],
#         [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730],
#         [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730],
#         [-0.0069,  0.0960,  0.0292,  ...,  0.6330,  1.3127, -0.3730]])

array([[-0.02885437,  0.06500244,  0.0181427 , ...,  0.63296866,
         1.3126814 ,  0.13159929],
       [-0.00243568,  0.01256561,  0.05722046, ...,  0.63296866,
         1.3126814 ,  0.13159929],
       [-0.00685501,  0.0960083 ,  0.0291748 , ...,  0.63296866,
         1.3126814 , -0.3729792 ],
       [-0.00685501,  0.0960083 ,  0.0291748 , ...,  0.63296866,
         1.3126814 , -0.3729792 ],
       [-0.00685501,  0.0960083 ,  0.0291748 , ...,  0.63296866,
         1.3126814 , -0.3729792 ]], dtype=float32)

In [ ]:
from tqdm import tqdm

# Data iterator (nao sei para que)

data_iterator = tqdm(
        static_dataloader,
        leave=True,
        unit="batch",
        postfix={
            "epo": -1,
            "acc": "%.4f" % 0.0,
            "lss": "%.8f" % 0.0,
            "dlb": "%.4f" % -1,
        },
        disable=False,
    )